### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by cn-404-not-found** [xuess/smzdm-sign#3]
root@ubuntu:/home/liangyong/smzdm# nodejs smzdm.js 
/home/liangyong/smzdm/smzdm.js:10
const { getRandom, ascii2native } = require('./lib/utils'); //工具类
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

烦请看看是什么问题，新手，谢谢

**Comment by xuess** [comment]
@cn-404-not-found  执行命令错误了，`node smzdm.js` 或者 `npm run dev` ，如果还有问题。试试先删掉 项目中 `node_modules` 文件夹，用`yarn` 安装依赖包试试。
如果没有 `yarn`，先`npm install -g yarn`，然后再执行 `yarn` 命令，具体可以搜一下 yarn用法。

**Comment by xuess** [comment]
@cn-404-not-found  如果还有问题，环境信息可以展示一下，这样好判断点。
